task of 21.11.2024 done
bakhodirsolieff/MobileApplicationsAssignment pull request #3
Opened 2024-11-22 10:46 UTC by bakhodirsolieff

**Changes made :**

- Successful registration(new user is present in CredentialsManager)
- Case Insensitive in email
- Email already used error

**Correct input values:**

- Password(digits)
- email format

"After successful registration, go to Login Activity"

2024-11-24 17:05 UTC, KamronGIT0319 approved these changes
Good

2024-11-24 17:05 UTC, KamronGIT0319 commented on app/src/main/java/com/example/myapplication/CredentialsManager.kt
I likel the idea of isemailalreadyused function which was not here before, and changing from class to object

2024-11-24 17:05 UTC, KamronGIT0319 commented on app/src/main/java/com/example/myapplication/SignUpDetailsActivity.kt
Shortening the line 15 is really time saving  a

2024-11-24 18:32 UTC, mkar-dev requested changes

2024-11-24 18:32 UTC, mkar-dev commented on app/src/main/java/com/example/myapplication/CredentialsManager.kt
> +    fun registerUser(email: String) {
If we are to use that credentials in login, don't we need a password here too?

2024-11-24 18:32 UTC, mkar-dev commented on app/src/test/java/com/example/myapplication/CredentialsManagerTest.kt
What about testing registerUser method?

2024-11-24 19:19 UTC, bakhodirsolieff commented on app/src/test/java/com/example/myapplication/CredentialsManagerTest.kt
fixed that by adding registerUser method in test class

2024-11-28 14:57 UTC, mkar-dev requested changes

2024-11-28 14:57 UTC, mkar-dev commented on app/src/main/java/com/example/myapplication/SignUpDetailsActivity.kt
> +        if (!credentialsManager.ValidateCredentialsForSignUp(
methods should be lowerCamelCase

2024-11-28 14:57 UTC, mkar-dev commented on app/src/main/java/com/example/myapplication/SignUpDetailsActivity.kt
> +        proceedToNextStep(email, password)
Can you find a better name for that method?

2024-11-28 14:57 UTC, mkar-dev commented on app/src/main/java/com/example/myapplication/SignUpDetailsActivity.kt
> +            setError(emailLayout, getString(R.string.error_email_already_used))
Duplicated code for displaying email already used
Can be simplified

2024-11-28 23:13 UTC, mtkar-dev commented on app/src/main/java/com/example/myapplication/FragmentA.kt
> +public class FragmentA : Fragment(R.layout.fragment_a) {
In Kotlin you don't need {} after constructor if the class body is empty

`public class FragmentA : Fragment(R.layout.fragment_a)`
is just enough

2024-11-28 23:13 UTC, mtkar-dev commented on app/src/main/java/com/example/myapplication/FragmentA.kt
> +
Unnecessary empty line

2024-11-28 23:13 UTC, mkar-dev commented on app/src/main/java/com/example/myapplication/CredentialsManager.kt
> +    fun validateLogin(email: String, password: String): Boolean {
I don't think you validate login here - but just login instead
I know we don't set the flag if the user is logged in yet, but generally the goal is to log in the user, not to see if he can log in

2024-11-28 23:22 UTC, mkar-dev requested changes

2024-11-28 23:22 UTC, mkar-dev commented on gradle/libs.versions.toml
> +androidx-fragments = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragments"}
Missing empty line below

2024-11-28 23:22 UTC, mkar-dev commented on app/src/test/java/com/example/myapplication/CredentialsManagerTest.kt
>          assertFalse(
If you removed the checkboxChecked check - that seems obsolete
Either the comment is misleading or that assertion is obsolete

2024-12-01 18:49 UTC, mkar-dev approved these changes
As in other case - remove what I commented and you're good to merge

2024-12-01 18:49 UTC, mkar-dev commented on gradle/libs.versions.toml
> +androidx-fragments = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragments" }
You forgot to remove those from your PR

2024-12-01 18:49 UTC, mkar-dev commented on app/src/test/java/com/example/myapplication/CredentialsManagerTest.kt
>          // Valid email, password, and checkbox checked
My bad, didn't see it
Another remain of checkbox checked

2024-12-01 18:50 UTC, mkar-dev commented on app/build.gradle.kts
> +    implementation(libs.androidx.fragments)
Also here

2024-12-02 09:40 UTC, bakhodirsolieff commented on app/build.gradle.kts
> +    implementation(libs.androidx.fragments)
Thanks for the review, i deleted that

2024-12-02 09:57 UTC, mkar-dev approved these changes

2024-12-03 09:53 UTC, KamronGIT0319 approved these changes

2024-12-03 09:53 UTC, KamronGIT0319 approved these changes
.

2024-12-03 09:54 UTC, KamronGIT0319 approved these changes

2024-12-03 09:54 UTC, KamronGIT0319 commented on app/src/main/AndroidManifest.xml
.

2024-12-03 09:54 UTC, KamronGIT0319 commented on app/src/main/java/com/example/myapplication/CreateAccountActivity.kt
>  import android.content.Intent
.

2024-12-03 09:54 UTC, KamronGIT0319 approved these changes
.

2024-12-03 09:57 UTC, KamronGIT0319 approved these changes
.

2024-12-03 10:10 UTC, merged